-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 04, 2025 at 05:05 AM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 8.1.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `mbj_feedback`
--

-- --------------------------------------------------------

--
-- Table structure for table `mbj`
--

CREATE TABLE `mbj` (
  `id` int(11) NOT NULL,
  `bil` varchar(255) DEFAULT NULL,
  `isu` longtext DEFAULT NULL,
  `tindakan` longtext DEFAULT NULL,
  `category` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `mbj`
--

INSERT INTO `mbj` (`id`, `bil`, `isu`, `tindakan`, `category`, `created_at`) VALUES
(2, 'Usul MBJ Bil 2/2023', '<p align=\"justify\"><strong>Tuntutan Cuti Gantian Kepada Pegawai Yang Bekerja Lebih Masa</strong><br />\r\n<br />\r\n4.1.1 Mesyuarat dimaklumkan bahawa berdasarkan Minit Bebas Pelaksanaan Kemudahan Cuti Gantian di BPSM KPM bertarikh 12 April 2023, Setiausaha Bahagian BPSM telah bersetuju dengan pelaksanaan kemudahan Cuti Gantian di BPSM berdasarkan perkara-perkara yang berikut:</p>\r\n\r\n<ol>\r\n	<li>Pegawai Kumpulan Pengurusan dan Profesional yang tidak layak menerima Bayaran Lebih Masa dan tidak dibayar bayaran khas lain;</li>\r\n	<li>Kumpulan Anggota Pelaksana yang tidak dibayar Bayaran Lebih Masa dan bayaran khas lain;</li>\r\n	<li>Kemudahan Cuti Gantian adalah tertakluk kepada kelulusan Ketua Jabatan. Oleh yang demikian, Ketua Jabatan hendaklah melihat kesesuaian pemberian Cuti Gantian berdasarkan tugas yang dilaksanakan dan tertakluk kepada kepentingan perkhidmatan; dan</li>\r\n	<li>Ketua-ketua Cawangan dikehendaki memastikan Cuti Gantian yang dimohon adalah berdasarkan tuntutan kerja lebih masa yang tidak diambil mempunyai sebab yang munasabah.</li>\r\n</ol>\r\n\r\n<p>4.1.2 Keputusan SUB BPSM tersebut telah dimaklumkan kepada Cawangan TW BPSM, KPM melalui memo rujukan KPM.500-5/1/16 Jld.2 (48) bertarikh 18 April 2023 untuk pemakluman kepada warga BPSM;<br />\r\n<br />\r\n4.1.3 TW memaklumkan bahawa hebahan berkenaan perkara ini ditangguhkan memandangkan mantan SUB BPSM memohon supaya syarat-syarat untuk kemudahan Cuti Gantian ini dibincangkan semula; dan<br />\r\n<br />\r\n4.1.4 Mesyuarat bersetuju agar Cawangan TW mengambil perhatian dan tindakan terhadap perkara 4.1.3.</p>\r\n', '<p align=\"justify\"><strong>Cawangan TW</strong><br />\r\n<br />\r\nHasil perbincangan dengan SUB SM mengenai Cuti Gantian kepada Pegawai Kumpulan Pengurusan dan Profesional (P&P) pada 22 November 2023 adalah seperti berikut:</p>\r\n\r\n<ol>\r\n	<li>Cuti Gantian boleh dipertimbangkan jika melibatkan acara/program berskala besar yang melibatkan keseluruhan tenaga kerja KPM. Contoh: Penganjuran MAHA, Penganjuran Sukan SEA dsb; dan</li>\r\n	<li>Cuti Gantian tidak dipertimbangkan jika melibatkan kerja-kerja / tugasan hakiki.</li>\r\n</ol>\r\n', 'sumbermanusia', '2024-06-27 02:46:41'),
(3, 'Usul MBJ Bil 2/2023', '<p><strong>Keberadaan Orang Awam di Aras 14, BPSM</strong><br />\r\n<br />\r\n5.2.1 Mesyuarat dimaklumkan bahawa terdapat orang awam yang tidak dikenali yang sering kali dilihat berlegar-legar dan menggunakan kemudahan di pantri di Aras 14;<br />\r\n<br />\r\n5.5.2 Mesyuarat memohon supaya satu mekanisme baharu dilaksanakan bagi menghalang individu tidak dikenali masuk ke ruang pejabat tanpa sebarang urusan memandangkan pas pelawat yang dibekalkan di Balai Pengawal di Aras 1 membenarkan pelawat mengakses ke semua aras di Blok E12; dan<br />\r\n<br />\r\n5.5.3 Mesyuarat bersetuju agar Cawangan TW mengambil tindakan dan perhatian terhadap perkara 5.5.2.</p>\r\n', '<p><strong>Cawangan TW</strong><br />\r\n<br />\r\nDimaklumkan bahawa Bahagian Khidmat Pengurusan (BKP) pada 8 Februari 2024 telah selesai melaksanakan pemurnian akses kad pelawat di Blok E12 di mana kad pelawat tersebut telah dihadkan kepada aras yang ingin dituju sahaja dan setiap aras telah diperuntukkan sebanyak 10 unit kad pelawat.</p>\r\n', 'sumbermanusia', '2024-06-27 07:52:55'),
(5, 'Usul MBJ Bil 2/2023', '<p align=\"justify\"><strong>Ruang Pejabat Yang Tidak Kondusif Di Cawangan Naik Pangkat Dan Cawangan Pembangunan Organisasi</strong><br />\r\n<br />\r\n6.1.1 YBrs. Pengerusi memaklumkan bahawa ruang pejabat di Cawangan Naik Pangkat dan Cawangan Pembangunan Organisasi tidak teratur dan padat;<br />\r\n<br />\r\n6.1.2 YBrs. Pengerusi mencadangkan supaya susun atur ruang pejabat di cawangan tersebut dikaji semula dan sekiranya perlu dicadangkan supaya satu unit daripada cawangan tersebut menumpang di mana-mana cawangan yang mempunyai ruang pejabat tambahan; dan<br />\r\n<br />\r\n6.1.3 Mesyuarat bersetuju agar Cawangan TW mengambil tindakan dan perhatian terhadap perkara 6.1.3.</p>\r\n', '<p align=\"justify\"><strong>Cawangan TW</strong><br />\r\n<br />\r\nDimaklumkan bahawa satu mesyuarat yang telah dipengerusikan oleh SUB BPSM telah diadakan pada 11 Januari 2024. Mesyuarat tersebut turut dihadiri oleh TSUBK (Pembangunan), TSUB TW, TSUB CNP, TSUB CLK dan TSUB CPO bersama wakil daripada BKP dan KCJ Engineering.<br />\r\n<br />\r\nSemasa mesyuarat tersebut, dimaklumkan bahawa satu sesi lawatan pengauditan ruang telah dilaksanakan pada 12 Disember 2023 dan hasil pengauditan ruang mendapati terdapat lebihan ruang sebanyak 181.78m2 di Aras 4 manakala lebihan ruang di Aras 14 adalah sebanyak 11.09m2</p>\r\n', 'pentadbiran', '2024-06-27 08:24:12'),
(6, 'Usul MBJ Bil 2/2023', '<p><strong>Perbezaan Semakan Dokumen TNT Pegawai dan Staf BPSM oleh PT (P/O) (Checker) di Cawangan TW</strong><br />\r\n<br />\r\n5.1.1 Mesyuarat dimaklumkan bahawa terdapat perbezaan tatacara semakan dokumen TNT oleh PT (P/O) (checker) di Cawangan TW yang menyebabkan tuntutan TNT dikuiri dan perlu dikemukakan semula beserta dokumen tambahan;<br />\r\n<br />\r\n5.1.2 TW memaklumkan bahawa arahan dalaman berkenaan senarai semak dan perkara berkaitan TNT pegawai sedang dibangunkan. TW akan membuat hebahan setelah perkara ini dimuktamadkan; dan<br />\r\n<br />\r\n5.1.3 Mesyuarat bersetuju agar Cawangan TW mengambil perhatian dan tindakan terhadap perkara 5.1.2.</p>\r\n', '<p><strong>Cawangan TW</strong><br />\r\n<br />\r\nSenarai semak dan borang tuntutan yang telah dikemaskini boleh diperoleh di portal KITA@BPSM. Hebahan mengenai perkara ini juga telah dibuat pada 19 Februari 2024. Diharapkan semua warga BPSM dapat mematuhi senarai semak yang telah disediakan.</p>\r\n', 'kewangan', '2024-06-28 01:24:40'),
(7, 'Usul MBJ Bil 2/2023', '<p align=\"justify\"><strong>Penganjuran Program Outdoor SUB, BPSM Bersama Pegawai BPSM</strong><br />\r\n<br />\r\n4.3.1 Mesyuarat dimaklumkan bahawa Program Outdoor SUB BPSM yang telah dirancang untuk diadakan pada 24 Jun 2023 terpaksa ditangguhkan berikutan faktor cuaca yang tidak menentu. KESKEP akan merancang semula program yang sesuai untuk dilaksanakan dengan mengambil kira perkembangan semasa; dan<br />\r\n<br />\r\n4.3.2 Mesyuarat bersetuju agar KESKEP mengambil perhatian dan tindakan terhadap perkara 4.3.1.</p>\r\n', '<p align=\"justify\"><strong>KESKEP</strong></p>\r\n\r\n<p align=\"justify\">KESKEP telah menganjurkan Karnival Permainan Dalaman (Indoor Games) bagi menggantikan program tersebut. Karnival yang telah diadakan pada 8 Februari 2024 itu juga adalah sebagai penutup program Kita@BPSM Aktif.</p>\r\n', 'kebajikan', '2024-06-28 01:26:28'),
(8, 'Usul MBJ Bil 2/2023', '<p><strong>Mempelbagaikan Informasi Hebahan E-mel</strong><br />\r\n<br />\r\n5.3.1 Mesyuarat dimaklumkan bahawa e-mel hebahan yang dilaksanakan oleh Cawangan TW tertumpu kepada maklumat berkaitan kesihatan dan penyakit sahaja; dan<br />\r\n<br />\r\n5.3.2 Mesyuarat memohon supaya hebahan tersebut dipelbagaikan merangkumi pekeliling-pekeliling dan dasar baharu kerajaan, sistem-sistem yang terdapat dalam BPSM dan KPM serta informasi-informasi lain;<br />\r\n<br />\r\n5.3.3 Mesyuarat bersetuju agar Cawangan TW mengambil tindakan dan perhatian terhadap perkara 5.3.2</p>\r\n', '<p><strong>Cawangan TW</strong><br />\r\n<br />\r\nDimaklumkan bahawa e-mel hebahan yang dilaksanakan oleh Cawangan TW adalah seperti berikut:<br />\r\n<br />\r\n<strong>Hari Isnin</strong>: Hebahan berkaitan kesihatan<br />\r\n<br />\r\n<strong>Hari Rabu</strong>: Hebahan berkaitan bahasa (pantun, peribahasa dan lain-lain)<br />\r\n<br />\r\n<strong>Hari Jumaat</strong>: Hebahan berkaitan sistem dalaman BPSM/ Pekeliling dan Dasar Jabatan Perkhidmatan Awam yang terkini.</p>\r\n', 'sumbermanusia', '2024-06-28 01:28:42'),
(9, 'Usul MBJ Bil 1/2024', '<p><strong>Mempelbagaikan</strong> <strong>Kursus</strong><strong>/ </strong><strong>Bengkel</strong><strong>/ </strong><strong>Aktiviti</strong><strong> Yang </strong><strong>Dianjurkan</strong><strong> Serta </strong><strong>Dilaksanakan</strong><strong> Di </strong><strong>Luar</strong> <strong>Pejabat</strong></p>\r\n\r\n<p>4.1.1&nbsp;Wakil Pihak Pekerja memohon pertimbangan supaya penganjuran kursus/bengkel/aktiviti berteraskan pasukan seperti Team Building dan Kursus Jati Diri diadakan untuk mengeratkan lagi silaturahim antara warga BPSM;</p>\r\n\r\n<p>4.1.2 Wakil pihak pekerja juga memohon pertimbangan supaya kursus/ bengkel/aktiviti yang dianjurkan dapat diadakan di luar pejabat seperti di Institut Latihan Awam (ILA) bagi meningkatkan motivasi warga BPSM menyertai kursus /bengkel/ aktiviti tersebut; dan</p>\r\n\r\n<p>4.1.3&nbsp;Mesyuarat bersetuju agar Cawangan TW mengambil tindakan dan perhatian terhadap perkara 4.1.1 dan 4.1.2.</p>\r\n', '<p><strong>Cawangan TW</strong></p>\r\n\r\n<p>Bagi tahun 2024, Cawangan TW telah menganjurkan 3 kursus bersifat fungsian seperti berikut:</p>\r\n\r\n<ol>\r\n	<li>Kursus Pengurusan Fail dan Rekod yang Efektif;</li>\r\n	<li>Kursus Pengurusan Perolehan Kerajaan; dan</li>\r\n	<li>Kursus Pengurusan Tatatertib dalam Perkhidmatan Awam</li>\r\n</ol>\r\n\r\n<p>Bagi perancangan kursus bersifat generik, kursus yang akan dilaksanakan dalam masa terdekat adalah Kursus Minda Sejahtera (Pengurusan Stres) pada 29-31 Julai 2024 di Akademi Pembangunan Belia Malaysia, Batu Gajah, Perak.</p>\r\n', 'kebajikan', '2024-07-29 01:16:05'),
(10, 'Usul MBJ Bil 1/2024', '<p><strong>Pemasangan</strong> <strong>Cermin</strong> <strong>Penghadang</strong><strong> di </strong><strong>Kaunter</strong><strong> Aras 4 dan Aras 5</strong></p>\r\n\r\n<p>4.2.1&nbsp;Wakil Pihak Pekerja memohon pertimbangan supaya cermin penghadang dapat dipasang di Kaunter Aras 4 dan Aras 5 bagi menjaga keselamatan kakitangan yang bertugas di kaunter;</p>\r\n\r\n<p>4.2.2&nbsp;Mesyuarat bersetuju dan tiada halangan untuk melaksanakan perolehan pemasangan penghadang cermin bergantung kepada peruntukan kewangan;</p>\r\n\r\n<p>4.2.3&nbsp;Mesyuarat turut membincangkan cadangan pemasangan kamera litar tertutup (CCTV) di kaunter-kaunter tersebut bagi memantau dan menjaga keselamatan;</p>\r\n\r\n<p>4.2.4&nbsp;Mesyuarat dimaklumkan mengenai pemasangan empat (4) unit CCTV oleh Cawangan TW di Aras 3 yang berjumlah RM766.20 dimana perolehan tersebut adalah secara adalah secara kutipan dalaman;</p>\r\n\r\n<p>4.2.5 Mesyuarat mencadangkan supaya pemasangan CCTV dipertimbangkan oleh cawangan-cawangan di Aras 4 dan Aras 5 sepertimana yang dilakukan Cawangan TW di Aras 3; dan</p>\r\n\r\n<p>4.2.6&nbsp;Mesyuarat bersetuju agar Cawangan TW mengambil tindakan dan perhatian terhadap perkara 4.2.2.</p>\r\n', '<p><strong>Cawangan TW</strong></p>\r\n\r\n<p>Cawangan TW telah menyemak peruntukan kewangan tahun 2024 dan mendapati bahawa cadangan pemasangan cermin penghadang tidak dapat dilaksanakan. Walau bagaimanapun, perkara ini telah diambil kira dalam permohonan Anggaran Belanja Mengurus (ABM) Tahun 2025.</p>\r\n', 'pentadbiran', '2024-07-29 01:21:32'),
(11, 'Usul MBJ Bil 1/2024', '<p><strong>Hebahan</strong> <strong>Berkenaan</strong><strong> Majlis Bersama </strong><strong>Jabatan</strong><strong> (MBJ) BPSM</strong></p>\r\n\r\n<p>5.1.1&nbsp;Wakil Pihak Pekerja mencadangkan supaya portal KITA@BPSM dijadikan medium hebahan dan pemakluman bagi aktiviti dan gerak kerja MBJ BPSM; dan</p>\r\n\r\n<p>5.1.2&nbsp;Mesyuarat bersetuju agar Cawangan TW mengambil perhatian dan tindakan terhadap perkara 5.1.1.</p>\r\n', '<p><strong>Cawangan TW</strong></p>\r\n\r\n<p>Dimaklumkan bahawa, Cawangan TW telah mewujudkan Paparan Maklum Balas MBJ BPSM melalui Portal KITA@BPSM.</p>\r\n\r\n<p>Berikut adalah pautan ke Paparan Maklum Balas MBJ BPSM: <a href=\"http://10.22.28.183/portal/maklum-balas-mbj-bpsm/\">http://10.22.28.183/portal/maklum-balas-mbj-bpsm/</a></p>\r\n\r\n<p><strong>Nota</strong>: Paparan Maklum Balas MBJ BPSM ini hanya boleh diakses melalui Intranet KPM sahaja.</p>\r\n', 'sumbermanusia', '2024-07-29 01:23:23'),
(12, 'Usul MBJ Bil 1/2024', '<p><strong>Dinding</strong> <strong>Basah</strong><strong> dan &lsquo;Wallpaper&rsquo; Yang </strong><strong>Rosak</strong></p>\r\n\r\n<p>5.2.1&nbsp;YBrs. Puan Pengerusi memaklumkan bahawa terdapat kesan resapan air hujan di dinding beberapa bilik di Aras 4 dan Aras 5. Kesan resapan tersebut telah menyebabkan wallpaper rosak dan koyak. Selain itu, dinding yang telah dibaiki telah ditinggalkan dalam keadaan yang masih berlubang;</p>\r\n\r\n<p>5.2.2&nbsp;YBrs. Puan Pengerusi memohon supaya Cawangan TW menghubungi pihak Bahagian Khidmat Pengurusan dan KCJ Engineering berkenaan masalah tersebut. Proses pembaikan dinding di Aras 4 sepatutnya telah selesai sepertimana komitmen yang telah diberikan oleh pihak KCJ Engineering semasa Mesyuarat &nbsp; Penyelarasan Isu-Isu Berkaitan Bangunan Blok E12 pada 11 Januari 2024 yang lalu; dan</p>\r\n\r\n<p>5.2.3&nbsp;Mesyuarat bersetuju agar Cawangan TW mengambil tindakan dan perhatian terhadap perkara 5.5.2.</p>\r\n', '<p><strong>Cawangan TW</strong></p>\r\n\r\n<p><strong><ins>Aras 4</ins><br />\r\nBilik Puan Muzaireen</strong> - Selesai<br />\r\n<strong>Bilik Puan Fairus</strong> &ndash; Kerja-kerja pembaikan kebocoran telah selesai dan wallpaper akan dipasang selepas tiada lagi kejadian kebocoran berulang.<br />\r\n<strong>Ruang Legar CNP (Unit TC1)</strong> - Kerja-kerja pembaikan kebocoran telah selesai, dan menunggu kerja-kerja pemasangan wallpaper.</p>\r\n\r\n<p><strong><ins>Aras &nbsp;5</ins> - Selesai sepenuhnya</strong><br />\r\nBilik Fail - Selesai<br />\r\nBilik Perbincangan Berlian - Selesai<br />\r\nBilik Puan Norhayati - Selesai<br />\r\nBilik Puan Hazlina - Selesai</p>\r\n', 'pentadbiran', '2024-07-29 01:27:53'),
(13, 'Usul MBJ Bil 2/2024', '<p><strong>CADANGAN UMUM PENAMBAHBAIKAN KAWALAN DALAMAN BPSM 5.1.1</strong></p>\r\n\r\n<p>Mesyuarat memohon supaya sebarang pengenalan atau pindaan kepada arahan kawalan dalaman yang baharu atau sedang berkuat kuasa (termasuk penggunaan borang baharu atau borang yang ditambah baik) perlu dimaklumkan melalui email bpsm.all@moe.gov.my dan aplikasi whatsapp KITA@BPSM KPM/ BPSM KPM bagi memastikan warga BPSM cakna berkenaan pengenalan/ penambah baikan terhadap kawalan dalaman tersebut;</p>\r\n\r\n<p>5.1.2 Mesyuarat bersetuju agar Cawangan TW mengambil perhatian dan tindakan terhadap perkara 5.1.1.</p>\r\n', '<p>Cawangan TW telah mengambil tindakan sewajarnya dalam mengemaskini sebarang penambahbaikan di dalam web KITA@BPSM berdasarkan perubahan dari semasa ke semasa. Selesai.</p>\r\n', 'pentadbiran', '2024-12-05 06:55:49'),
(14, 'Usul MBJ Bil 2/2024', '<p><strong>CADANGAN PENAMBAHBAIKAN KAWALAN DALAMAN BPSM BAGI TUNTUTAN PERJALANAN DALAM NEGERI</strong></p>\r\n\r\n<p>5.2.1 Mesyuarat memohon pengurangan redundancy dokumen tuntutan perjalanan dalam negeri terutamanya berkaitan salinan transaksi dalam talian, penyata kad kredit, resit cetakan daripada mesin terminal kad debit/kredit, penyata touch n&rsquo; go dan lain-lain bukti bayaran dan sekiranya salah satu dokumen telah dilampirkan, maka tiada keperluan untuk dokumen tambahan lain untuk turut dilampirkan bersama dapat ditambah baik;</p>\r\n\r\n<p>5.2.2 Mesyuarat bersetuju agar satu taklimat/ hebahan dilaksanakan bagi meningkatkan pemahaman berkenaan sebarang perubahan prosedur tuntutan; dan 5.2.3 Mesyuarat bersetuju agar Cawangan TW mengambil perhatian dan tindakan terhadap perkara 5.2.2.</p>\r\n', '<p>Cawangan TW mengambil maklum cadangan ini dan akan memastikan tiada redundancy dalam penyediaan dokumendokumen bagi tujuan tuntutan perjalanan. Walau bagaimanapun dokumen tambahan atau penjelasan lanjut akan diminta sekiranya terdapat query bagi sesuatu tuntutan. Cawangan TW merancang untuk mengadakan taklimat kepada semua kakitangan BPSM bagi menjelaskan perkara ini. Selesai.</p>\r\n', 'kewangan', '2024-12-05 06:59:21'),
(15, 'Usul MBJ Bil 2/2024', '<p><strong>LAWATAN PENANDA ARAS</strong></p>\r\n\r\n<p>5.3.1 Mesyuarat memohon supaya satu lawatan penanda aras dilaksanakan di institusi/jabatan lain bagi meningkatkan ilmu pengetahuan warga BPSM; dan</p>\r\n\r\n<p>5.2.1 Mesyuarat bersetuju agar Cawangan TW mengambil perhatian dan tindakan terhadap perkara 5.3.1.</p>\r\n', '<p>Lawatan penanda aras akan dilaksanakan mengikut keperluan dan fungsi cawangan. Setiap cawangan boleh mengemukakan cadangan untuk pertimbangan dan kelulusan ketua jabatan. Selesai.</p>\r\n', 'kebajikan', '2024-12-05 07:05:28'),
(16, 'Usul MBJ Bil 2/2024', '<p><strong>PERMOHONAN TUNTUTAN SECARA BAYAR DAN TUNTUT (PAY AND CLAIM) BAGI TEMPAT LETAK KENDERAAN (TLK) BERBAYAR DI KOMPLEKS E2 (BELAKANG AUDITORIUM) DAN TLK AWAM MENUJU KELUAR KE PINTU ALAMANDA</strong></p>\r\n\r\n<p>5.4.1 Mesyuarat memohon supaya BPSM membuka semula kemudahan tuntutan secara bayar dan tuntut (pay and claim) bagi TLK awam di Kompleks E2 (belakang auditorium) dan TLK awam menuju keluar ke pintu Alamanda (berhadapan Kompleks E13) bagi meringankan beban warga BPSM;</p>\r\n\r\n<p>5.4.2 Mesyuarat bersetuju agar usul ini dibawa ke peringkat MBJ KPM kerana melibatkan keseluruhan warga KPM di Kompleks E; dan</p>\r\n\r\n<p>5.4.3 Mesyuarat bersetuju agar Cawangan K mengambil perhatian dan tindakan terhadap perkara 5.4.2.</p>\r\n', '<p>Untuk makluman, kontrak TLK awam di Kompleks E2 (belakang auditorium) tidak lagi disambung oleh pihak BKP dimana kontrak sebelum ni adalah secara berpusat dan terdapat tuntutan palsu yang dibuat oleh pihak Pengurusan Parkir yang menyebabkan kontrak tersebut tidak disambung atas arahan KSU. Manakala, bagi kemudahan tuntutan secara bayar dan tuntut (pay and claim) bagi TLK awam di Kompleks E2 (belakang auditorium) dan TLK awam menuju keluar ke pintu Alamanda (berhadapan Kompleks E13) bergantung kepada PTJ masing-masing.</p>\r\n', 'kewangan', '2024-12-05 07:06:24'),
(17, 'Usul MBJ Bil 2/2024', '<p><strong>KEUTAMAAN DALAM PENGGUNAAN KENDERAAN JABATAN BAGI TUJUAN TUGAS RASMI KE PARLIMEN</strong></p>\r\n\r\n<p>5.5.1 Mesyuarat memohon supaya sebuah kenderaan jabatan dikhaskan (standby) bagi tujuan urusan Parlimen sepanjang tempoh Dewan Negara dan Dewan Rakyat bersidang;</p>\r\n\r\n<p>5.5.2 dan Mesyuarat bersetuju agar Cawangan TW mengambil perhatian dan tindakan terhadap perkara 5.5.1.</p>\r\n', '<p>Cawangan TW telah menyediakan sebuah kenderaan bagi tujuan ke Parlimen mengikut tarikh-tarikh yang telah diberikan kepada Cawangan TW</p>\r\n', 'pentadbiran', '2024-12-05 07:07:06'),
(18, 'Usul MBJ Bil 2/2024', '<p><strong>MAKLUM BALAS MBJ</strong></p>\r\n\r\n<p>6.1.1 Mesyuarat mencadangkan supaya maklum balas MBJ dipaparkan semasa mesyuarat dan diedarkan sebelum mesyuarat bersidang; dan</p>\r\n\r\n<p>6.1.2 Mesyuarat bersetuju agar Cawangan TW mengambil perhatian dan tindakan terhadap perkara 6.1.1.</p>\r\n', '<p>Cawangan TW telah menyediakan ruangan maklum balas MBJ di dalam web KITA@BPSM dan ruangan ini akan dikemaskini dari semasa ke semasa mengikut keperluan. Selesai.</p>\r\n', 'lainlain', '2024-12-05 07:07:50');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `mbj`
--
ALTER TABLE `mbj`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `mbj`
--
ALTER TABLE `mbj`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=19;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
